// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: fastpath.proto

package fastpathv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeState int32

const (
	RuntimeState_RUNTIME_STATE_UNSPECIFIED RuntimeState = 0
	RuntimeState_RUNTIME_STATE_UNKNOWN     RuntimeState = 1
	RuntimeState_RUNTIME_STATE_PENDING     RuntimeState = 2
	RuntimeState_RUNTIME_STATE_CREATING    RuntimeState = 3
	RuntimeState_RUNTIME_STATE_READY       RuntimeState = 4
	RuntimeState_RUNTIME_STATE_STOPPING    RuntimeState = 5
	RuntimeState_RUNTIME_STATE_STOPPED     RuntimeState = 6
	RuntimeState_RUNTIME_STATE_FAILED      RuntimeState = 7
	RuntimeState_RUNTIME_STATE_UNAVAILABLE RuntimeState = 8
	RuntimeState_RUNTIME_STATE_PAUSING     RuntimeState = 9
	RuntimeState_RUNTIME_STATE_PAUSED      RuntimeState = 10
	RuntimeState_RUNTIME_STATE_RESUMING    RuntimeState = 11
)

// Enum value maps for RuntimeState.
var (
	RuntimeState_name = map[int32]string{
		0:  "RUNTIME_STATE_UNSPECIFIED",
		1:  "RUNTIME_STATE_UNKNOWN",
		2:  "RUNTIME_STATE_PENDING",
		3:  "RUNTIME_STATE_CREATING",
		4:  "RUNTIME_STATE_READY",
		5:  "RUNTIME_STATE_STOPPING",
		6:  "RUNTIME_STATE_STOPPED",
		7:  "RUNTIME_STATE_FAILED",
		8:  "RUNTIME_STATE_UNAVAILABLE",
		9:  "RUNTIME_STATE_PAUSING",
		10: "RUNTIME_STATE_PAUSED",
		11: "RUNTIME_STATE_RESUMING",
	}
	RuntimeState_value = map[string]int32{
		"RUNTIME_STATE_UNSPECIFIED": 0,
		"RUNTIME_STATE_UNKNOWN":     1,
		"RUNTIME_STATE_PENDING":     2,
		"RUNTIME_STATE_CREATING":    3,
		"RUNTIME_STATE_READY":       4,
		"RUNTIME_STATE_STOPPING":    5,
		"RUNTIME_STATE_STOPPED":     6,
		"RUNTIME_STATE_FAILED":      7,
		"RUNTIME_STATE_UNAVAILABLE": 8,
		"RUNTIME_STATE_PAUSING":     9,
		"RUNTIME_STATE_PAUSED":      10,
		"RUNTIME_STATE_RESUMING":    11,
	}
)

func (x RuntimeState) Enum() *RuntimeState {
	p := new(RuntimeState)
	*p = x
	return p
}

func (x RuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_fastpath_proto_enumTypes[0].Descriptor()
}

func (RuntimeState) Type() protoreflect.EnumType {
	return &file_fastpath_proto_enumTypes[0]
}

func (x RuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeState.Descriptor instead.
func (RuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{0}
}

type SandboxState int32

const (
	SandboxState_SANDBOX_STATE_UNSPECIFIED SandboxState = 0
	SandboxState_SANDBOX_STATE_RUNNING     SandboxState = 1
	SandboxState_SANDBOX_STATE_PAUSED      SandboxState = 2
)

// Enum value maps for SandboxState.
var (
	SandboxState_name = map[int32]string{
		0: "SANDBOX_STATE_UNSPECIFIED",
		1: "SANDBOX_STATE_RUNNING",
		2: "SANDBOX_STATE_PAUSED",
	}
	SandboxState_value = map[string]int32{
		"SANDBOX_STATE_UNSPECIFIED": 0,
		"SANDBOX_STATE_RUNNING":     1,
		"SANDBOX_STATE_PAUSED":      2,
	}
)

func (x SandboxState) Enum() *SandboxState {
	p := new(SandboxState)
	*p = x
	return p
}

func (x SandboxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxState) Descriptor() protoreflect.EnumDescriptor {
	return file_fastpath_proto_enumTypes[1].Descriptor()
}

func (SandboxState) Type() protoreflect.EnumType {
	return &file_fastpath_proto_enumTypes[1]
}

func (x SandboxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxState.Descriptor instead.
func (SandboxState) EnumDescriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{1}
}

type DataPlaneState int32

const (
	DataPlaneState_DATA_PLANE_STATE_UNSPECIFIED DataPlaneState = 0
	DataPlaneState_DATA_PLANE_STATE_UNKNOWN     DataPlaneState = 1
	DataPlaneState_DATA_PLANE_STATE_PENDING     DataPlaneState = 2
	DataPlaneState_DATA_PLANE_STATE_PUBLISHING  DataPlaneState = 3
	DataPlaneState_DATA_PLANE_STATE_READY       DataPlaneState = 4
	DataPlaneState_DATA_PLANE_STATE_DRAINING    DataPlaneState = 5
	DataPlaneState_DATA_PLANE_STATE_FAILED      DataPlaneState = 6
	DataPlaneState_DATA_PLANE_STATE_UNAVAILABLE DataPlaneState = 7
)

// Enum value maps for DataPlaneState.
var (
	DataPlaneState_name = map[int32]string{
		0: "DATA_PLANE_STATE_UNSPECIFIED",
		1: "DATA_PLANE_STATE_UNKNOWN",
		2: "DATA_PLANE_STATE_PENDING",
		3: "DATA_PLANE_STATE_PUBLISHING",
		4: "DATA_PLANE_STATE_READY",
		5: "DATA_PLANE_STATE_DRAINING",
		6: "DATA_PLANE_STATE_FAILED",
		7: "DATA_PLANE_STATE_UNAVAILABLE",
	}
	DataPlaneState_value = map[string]int32{
		"DATA_PLANE_STATE_UNSPECIFIED": 0,
		"DATA_PLANE_STATE_UNKNOWN":     1,
		"DATA_PLANE_STATE_PENDING":     2,
		"DATA_PLANE_STATE_PUBLISHING":  3,
		"DATA_PLANE_STATE_READY":       4,
		"DATA_PLANE_STATE_DRAINING":    5,
		"DATA_PLANE_STATE_FAILED":      6,
		"DATA_PLANE_STATE_UNAVAILABLE": 7,
	}
)

func (x DataPlaneState) Enum() *DataPlaneState {
	p := new(DataPlaneState)
	*p = x
	return p
}

func (x DataPlaneState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataPlaneState) Descriptor() protoreflect.EnumDescriptor {
	return file_fastpath_proto_enumTypes[2].Descriptor()
}

func (DataPlaneState) Type() protoreflect.EnumType {
	return &file_fastpath_proto_enumTypes[2]
}

func (x DataPlaneState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataPlaneState.Descriptor instead.
func (DataPlaneState) EnumDescriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{2}
}

type EndpointAccessMode int32

const (
	EndpointAccessMode_CENTRAL_PROXY        EndpointAccessMode = 0
	EndpointAccessMode_DIRECT_FASTLET_PROXY EndpointAccessMode = 1
)

// Enum value maps for EndpointAccessMode.
var (
	EndpointAccessMode_name = map[int32]string{
		0: "CENTRAL_PROXY",
		1: "DIRECT_FASTLET_PROXY",
	}
	EndpointAccessMode_value = map[string]int32{
		"CENTRAL_PROXY":        0,
		"DIRECT_FASTLET_PROXY": 1,
	}
)

func (x EndpointAccessMode) Enum() *EndpointAccessMode {
	p := new(EndpointAccessMode)
	*p = x
	return p
}

func (x EndpointAccessMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointAccessMode) Descriptor() protoreflect.EnumDescriptor {
	return file_fastpath_proto_enumTypes[3].Descriptor()
}

func (EndpointAccessMode) Type() protoreflect.EnumType {
	return &file_fastpath_proto_enumTypes[3]
}

func (x EndpointAccessMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointAccessMode.Descriptor instead.
func (EndpointAccessMode) EnumDescriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{3}
}

type NamespacedName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespacedName) Reset() {
	*x = NamespacedName{}
	mi := &file_fastpath_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespacedName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacedName) ProtoMessage() {}

func (x *NamespacedName) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacedName.ProtoReflect.Descriptor instead.
func (*NamespacedName) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{0}
}

func (x *NamespacedName) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespacedName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SandboxReference struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NamespacedName *NamespacedName        `protobuf:"bytes,2,opt,name=namespaced_name,json=namespacedName,proto3" json:"namespaced_name,omitempty"`
	ExpectedUid    string                 `protobuf:"bytes,3,opt,name=expected_uid,json=expectedUid,proto3" json:"expected_uid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxReference) Reset() {
	*x = SandboxReference{}
	mi := &file_fastpath_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxReference) ProtoMessage() {}

func (x *SandboxReference) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxReference.ProtoReflect.Descriptor instead.
func (*SandboxReference) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxReference) GetNamespacedName() *NamespacedName {
	if x != nil {
		return x.NamespacedName
	}
	return nil
}

func (x *SandboxReference) GetExpectedUid() string {
	if x != nil {
		return x.ExpectedUid
	}
	return ""
}

type SandboxIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxIdentity) Reset() {
	*x = SandboxIdentity{}
	mi := &file_fastpath_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxIdentity) ProtoMessage() {}

func (x *SandboxIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxIdentity.ProtoReflect.Descriptor instead.
func (*SandboxIdentity) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{2}
}

func (x *SandboxIdentity) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *SandboxIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SandboxIdentity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type RuntimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         RuntimeState           `protobuf:"varint,1,opt,name=state,proto3,enum=fastpath.v2.RuntimeState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_fastpath_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeInfo) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

type DataPlaneInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         DataPlaneState         `protobuf:"varint,1,opt,name=state,proto3,enum=fastpath.v2.DataPlaneState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPlaneInfo) Reset() {
	*x = DataPlaneInfo{}
	mi := &file_fastpath_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPlaneInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPlaneInfo) ProtoMessage() {}

func (x *DataPlaneInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPlaneInfo.ProtoReflect.Descriptor instead.
func (*DataPlaneInfo) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{4}
}

func (x *DataPlaneInfo) GetState() DataPlaneState {
	if x != nil {
		return x.State
	}
	return DataPlaneState_DATA_PLANE_STATE_UNSPECIFIED
}

type CheckpointInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId      string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	ManifestRef       string                 `protobuf:"bytes,2,opt,name=manifest_ref,json=manifestRef,proto3" json:"manifest_ref,omitempty"`
	ArtifactDigest    string                 `protobuf:"bytes,3,opt,name=artifact_digest,json=artifactDigest,proto3" json:"artifact_digest,omitempty"`
	SizeBytes         int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	PausedUnixSeconds int64                  `protobuf:"varint,5,opt,name=paused_unix_seconds,json=pausedUnixSeconds,proto3" json:"paused_unix_seconds,omitempty"`
	FastletName       string                 `protobuf:"bytes,6,opt,name=fastlet_name,json=fastletName,proto3" json:"fastlet_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckpointInfo) Reset() {
	*x = CheckpointInfo{}
	mi := &file_fastpath_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointInfo) ProtoMessage() {}

func (x *CheckpointInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointInfo.ProtoReflect.Descriptor instead.
func (*CheckpointInfo) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{5}
}

func (x *CheckpointInfo) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *CheckpointInfo) GetManifestRef() string {
	if x != nil {
		return x.ManifestRef
	}
	return ""
}

func (x *CheckpointInfo) GetArtifactDigest() string {
	if x != nil {
		return x.ArtifactDigest
	}
	return ""
}

func (x *CheckpointInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CheckpointInfo) GetPausedUnixSeconds() int64 {
	if x != nil {
		return x.PausedUnixSeconds
	}
	return 0
}

func (x *CheckpointInfo) GetFastletName() string {
	if x != nil {
		return x.FastletName
	}
	return ""
}

type SandboxInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Identity          *SandboxIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	AppliedGeneration int64                  `protobuf:"varint,2,opt,name=applied_generation,json=appliedGeneration,proto3" json:"applied_generation,omitempty"`
	Runtime           *RuntimeInfo           `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	DataPlane         *DataPlaneInfo         `protobuf:"bytes,4,opt,name=data_plane,json=dataPlane,proto3" json:"data_plane,omitempty"`
	Ready             bool                   `protobuf:"varint,7,opt,name=ready,proto3" json:"ready,omitempty"`
	State             SandboxState           `protobuf:"varint,8,opt,name=state,proto3,enum=fastpath.v2.SandboxState" json:"state,omitempty"`
	Checkpoint        *CheckpointInfo        `protobuf:"bytes,9,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	mi := &file_fastpath_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo.ProtoReflect.Descriptor instead.
func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{6}
}

func (x *SandboxInfo) GetIdentity() *SandboxIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *SandboxInfo) GetAppliedGeneration() int64 {
	if x != nil {
		return x.AppliedGeneration
	}
	return 0
}

func (x *SandboxInfo) GetRuntime() *RuntimeInfo {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *SandboxInfo) GetDataPlane() *DataPlaneInfo {
	if x != nil {
		return x.DataPlane
	}
	return nil
}

func (x *SandboxInfo) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *SandboxInfo) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

func (x *SandboxInfo) GetCheckpoint() *CheckpointInfo {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

type GetSandboxRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Sandbox            *SandboxReference      `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	ExpectedGeneration int64                  `protobuf:"varint,2,opt,name=expected_generation,json=expectedGeneration,proto3" json:"expected_generation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	mi := &file_fastpath_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{7}
}

func (x *GetSandboxRequest) GetSandbox() *SandboxReference {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *GetSandboxRequest) GetExpectedGeneration() int64 {
	if x != nil {
		return x.ExpectedGeneration
	}
	return 0
}

type GetSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *SandboxInfo           `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Generation    int64                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxResponse) Reset() {
	*x = GetSandboxResponse{}
	mi := &file_fastpath_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxResponse) ProtoMessage() {}

func (x *GetSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxResponse) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{8}
}

func (x *GetSandboxResponse) GetSandbox() *SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *GetSandboxResponse) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type ResumeSandboxRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequestId            string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Sandbox              *SandboxReference      `protobuf:"bytes,2,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	ExpectedGeneration   int64                  `protobuf:"varint,3,opt,name=expected_generation,json=expectedGeneration,proto3" json:"expected_generation,omitempty"`
	ExpectedCheckpointId string                 `protobuf:"bytes,4,opt,name=expected_checkpoint_id,json=expectedCheckpointId,proto3" json:"expected_checkpoint_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResumeSandboxRequest) Reset() {
	*x = ResumeSandboxRequest{}
	mi := &file_fastpath_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxRequest) ProtoMessage() {}

func (x *ResumeSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxRequest.ProtoReflect.Descriptor instead.
func (*ResumeSandboxRequest) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{9}
}

func (x *ResumeSandboxRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResumeSandboxRequest) GetSandbox() *SandboxReference {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *ResumeSandboxRequest) GetExpectedGeneration() int64 {
	if x != nil {
		return x.ExpectedGeneration
	}
	return 0
}

func (x *ResumeSandboxRequest) GetExpectedCheckpointId() string {
	if x != nil {
		return x.ExpectedCheckpointId
	}
	return ""
}

type ResumeSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *SandboxInfo           `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Generation    int64                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSandboxResponse) Reset() {
	*x = ResumeSandboxResponse{}
	mi := &file_fastpath_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxResponse) ProtoMessage() {}

func (x *ResumeSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxResponse.ProtoReflect.Descriptor instead.
func (*ResumeSandboxResponse) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{10}
}

func (x *ResumeSandboxResponse) GetSandbox() *SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *ResumeSandboxResponse) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type EndpointTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*EndpointTarget_ComponentName
	//	*EndpointTarget_Port
	Target        isEndpointTarget_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointTarget) Reset() {
	*x = EndpointTarget{}
	mi := &file_fastpath_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointTarget) ProtoMessage() {}

func (x *EndpointTarget) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointTarget.ProtoReflect.Descriptor instead.
func (*EndpointTarget) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{11}
}

func (x *EndpointTarget) GetTarget() isEndpointTarget_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EndpointTarget) GetComponentName() string {
	if x != nil {
		if x, ok := x.Target.(*EndpointTarget_ComponentName); ok {
			return x.ComponentName
		}
	}
	return ""
}

func (x *EndpointTarget) GetPort() uint32 {
	if x != nil {
		if x, ok := x.Target.(*EndpointTarget_Port); ok {
			return x.Port
		}
	}
	return 0
}

type isEndpointTarget_Target interface {
	isEndpointTarget_Target()
}

type EndpointTarget_ComponentName struct {
	ComponentName string `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3,oneof"`
}

type EndpointTarget_Port struct {
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3,oneof"`
}

func (*EndpointTarget_ComponentName) isEndpointTarget_Target() {}

func (*EndpointTarget_Port) isEndpointTarget_Target() {}

type ResolveEndpointRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Sandbox            *SandboxReference      `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Target             *EndpointTarget        `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	AccessMode         EndpointAccessMode     `protobuf:"varint,3,opt,name=access_mode,json=accessMode,proto3,enum=fastpath.v2.EndpointAccessMode" json:"access_mode,omitempty"`
	ExpectedGeneration int64                  `protobuf:"varint,4,opt,name=expected_generation,json=expectedGeneration,proto3" json:"expected_generation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResolveEndpointRequest) Reset() {
	*x = ResolveEndpointRequest{}
	mi := &file_fastpath_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEndpointRequest) ProtoMessage() {}

func (x *ResolveEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEndpointRequest.ProtoReflect.Descriptor instead.
func (*ResolveEndpointRequest) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveEndpointRequest) GetSandbox() *SandboxReference {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *ResolveEndpointRequest) GetTarget() *EndpointTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ResolveEndpointRequest) GetAccessMode() EndpointAccessMode {
	if x != nil {
		return x.AccessMode
	}
	return EndpointAccessMode_CENTRAL_PROXY
}

func (x *ResolveEndpointRequest) GetExpectedGeneration() int64 {
	if x != nil {
		return x.ExpectedGeneration
	}
	return 0
}

type ResolvedEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentName string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedEndpoint) Reset() {
	*x = ResolvedEndpoint{}
	mi := &file_fastpath_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedEndpoint) ProtoMessage() {}

func (x *ResolvedEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedEndpoint.ProtoReflect.Descriptor instead.
func (*ResolvedEndpoint) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{13}
}

func (x *ResolvedEndpoint) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ResolvedEndpoint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ResolvedEndpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ResolveEndpointResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SandboxUid           string                 `protobuf:"bytes,1,opt,name=sandbox_uid,json=sandboxUid,proto3" json:"sandbox_uid,omitempty"`
	Endpoint             *ResolvedEndpoint      `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ProxyEndpoint        string                 `protobuf:"bytes,3,opt,name=proxy_endpoint,json=proxyEndpoint,proto3" json:"proxy_endpoint,omitempty"`
	RequiredHeaders      map[string]string      `protobuf:"bytes,4,rep,name=required_headers,json=requiredHeaders,proto3" json:"required_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RouteGeneration      int64                  `protobuf:"varint,5,opt,name=route_generation,json=routeGeneration,proto3" json:"route_generation,omitempty"`
	ExpiresAtUnixSeconds int64                  `protobuf:"varint,6,opt,name=expires_at_unix_seconds,json=expiresAtUnixSeconds,proto3" json:"expires_at_unix_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResolveEndpointResponse) Reset() {
	*x = ResolveEndpointResponse{}
	mi := &file_fastpath_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEndpointResponse) ProtoMessage() {}

func (x *ResolveEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEndpointResponse.ProtoReflect.Descriptor instead.
func (*ResolveEndpointResponse) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{14}
}

func (x *ResolveEndpointResponse) GetSandboxUid() string {
	if x != nil {
		return x.SandboxUid
	}
	return ""
}

func (x *ResolveEndpointResponse) GetEndpoint() *ResolvedEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *ResolveEndpointResponse) GetProxyEndpoint() string {
	if x != nil {
		return x.ProxyEndpoint
	}
	return ""
}

func (x *ResolveEndpointResponse) GetRequiredHeaders() map[string]string {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

func (x *ResolveEndpointResponse) GetRouteGeneration() int64 {
	if x != nil {
		return x.RouteGeneration
	}
	return 0
}

func (x *ResolveEndpointResponse) GetExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.ExpiresAtUnixSeconds
	}
	return 0
}

var File_fastpath_proto protoreflect.FileDescriptor

const file_fastpath_proto_rawDesc = "" +
	"\n" +
	"\x0efastpath.proto\x12\vfastpath.v2\"B\n" +
	"\x0eNamespacedName\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"{\n" +
	"\x10SandboxReference\x12D\n" +
	"\x0fnamespaced_name\x18\x02 \x01(\v2\x1b.fastpath.v2.NamespacedNameR\x0enamespacedName\x12!\n" +
	"\fexpected_uid\x18\x03 \x01(\tR\vexpectedUid\"U\n" +
	"\x0fSandboxIdentity\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\">\n" +
	"\vRuntimeInfo\x12/\n" +
	"\x05state\x18\x01 \x01(\x0e2\x19.fastpath.v2.RuntimeStateR\x05state\"B\n" +
	"\rDataPlaneInfo\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.fastpath.v2.DataPlaneStateR\x05state\"\xf3\x01\n" +
	"\x0eCheckpointInfo\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12!\n" +
	"\fmanifest_ref\x18\x02 \x01(\tR\vmanifestRef\x12'\n" +
	"\x0fartifact_digest\x18\x03 \x01(\tR\x0eartifactDigest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12.\n" +
	"\x13paused_unix_seconds\x18\x05 \x01(\x03R\x11pausedUnixSeconds\x12!\n" +
	"\ffastlet_name\x18\x06 \x01(\tR\vfastletName\"\xf5\x02\n" +
	"\vSandboxInfo\x128\n" +
	"\bidentity\x18\x01 \x01(\v2\x1c.fastpath.v2.SandboxIdentityR\bidentity\x12-\n" +
	"\x12applied_generation\x18\x02 \x01(\x03R\x11appliedGeneration\x122\n" +
	"\aruntime\x18\x03 \x01(\v2\x18.fastpath.v2.RuntimeInfoR\aruntime\x129\n" +
	"\n" +
	"data_plane\x18\x04 \x01(\v2\x1a.fastpath.v2.DataPlaneInfoR\tdataPlane\x12\x14\n" +
	"\x05ready\x18\a \x01(\bR\x05ready\x12/\n" +
	"\x05state\x18\b \x01(\x0e2\x19.fastpath.v2.SandboxStateR\x05state\x12;\n" +
	"\n" +
	"checkpoint\x18\t \x01(\v2\x1b.fastpath.v2.CheckpointInfoR\n" +
	"checkpointJ\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"}\n" +
	"\x11GetSandboxRequest\x127\n" +
	"\asandbox\x18\x01 \x01(\v2\x1d.fastpath.v2.SandboxReferenceR\asandbox\x12/\n" +
	"\x13expected_generation\x18\x02 \x01(\x03R\x12expectedGeneration\"h\n" +
	"\x12GetSandboxResponse\x122\n" +
	"\asandbox\x18\x01 \x01(\v2\x18.fastpath.v2.SandboxInfoR\asandbox\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x03R\n" +
	"generation\"\xd5\x01\n" +
	"\x14ResumeSandboxRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x127\n" +
	"\asandbox\x18\x02 \x01(\v2\x1d.fastpath.v2.SandboxReferenceR\asandbox\x12/\n" +
	"\x13expected_generation\x18\x03 \x01(\x03R\x12expectedGeneration\x124\n" +
	"\x16expected_checkpoint_id\x18\x04 \x01(\tR\x14expectedCheckpointId\"k\n" +
	"\x15ResumeSandboxResponse\x122\n" +
	"\asandbox\x18\x01 \x01(\v2\x18.fastpath.v2.SandboxInfoR\asandbox\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x03R\n" +
	"generation\"Y\n" +
	"\x0eEndpointTarget\x12'\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tH\x00R\rcomponentName\x12\x14\n" +
	"\x04port\x18\x02 \x01(\rH\x00R\x04portB\b\n" +
	"\x06target\"\xf9\x01\n" +
	"\x16ResolveEndpointRequest\x127\n" +
	"\asandbox\x18\x01 \x01(\v2\x1d.fastpath.v2.SandboxReferenceR\asandbox\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.fastpath.v2.EndpointTargetR\x06target\x12@\n" +
	"\vaccess_mode\x18\x03 \x01(\x0e2\x1f.fastpath.v2.EndpointAccessModeR\n" +
	"accessMode\x12/\n" +
	"\x13expected_generation\x18\x04 \x01(\x03R\x12expectedGeneration\"i\n" +
	"\x10ResolvedEndpoint\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"\xa8\x03\n" +
	"\x17ResolveEndpointResponse\x12\x1f\n" +
	"\vsandbox_uid\x18\x01 \x01(\tR\n" +
	"sandboxUid\x129\n" +
	"\bendpoint\x18\x02 \x01(\v2\x1d.fastpath.v2.ResolvedEndpointR\bendpoint\x12%\n" +
	"\x0eproxy_endpoint\x18\x03 \x01(\tR\rproxyEndpoint\x12d\n" +
	"\x10required_headers\x18\x04 \x03(\v29.fastpath.v2.ResolveEndpointResponse.RequiredHeadersEntryR\x0frequiredHeaders\x12)\n" +
	"\x10route_generation\x18\x05 \x01(\x03R\x0frouteGeneration\x125\n" +
	"\x17expires_at_unix_seconds\x18\x06 \x01(\x03R\x14expiresAtUnixSeconds\x1aB\n" +
	"\x14RequiredHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xd9\x02\n" +
	"\fRuntimeState\x12\x1d\n" +
	"\x19RUNTIME_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RUNTIME_STATE_UNKNOWN\x10\x01\x12\x19\n" +
	"\x15RUNTIME_STATE_PENDING\x10\x02\x12\x1a\n" +
	"\x16RUNTIME_STATE_CREATING\x10\x03\x12\x17\n" +
	"\x13RUNTIME_STATE_READY\x10\x04\x12\x1a\n" +
	"\x16RUNTIME_STATE_STOPPING\x10\x05\x12\x19\n" +
	"\x15RUNTIME_STATE_STOPPED\x10\x06\x12\x18\n" +
	"\x14RUNTIME_STATE_FAILED\x10\a\x12\x1d\n" +
	"\x19RUNTIME_STATE_UNAVAILABLE\x10\b\x12\x19\n" +
	"\x15RUNTIME_STATE_PAUSING\x10\t\x12\x18\n" +
	"\x14RUNTIME_STATE_PAUSED\x10\n" +
	"\x12\x1a\n" +
	"\x16RUNTIME_STATE_RESUMING\x10\v*b\n" +
	"\fSandboxState\x12\x1d\n" +
	"\x19SANDBOX_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SANDBOX_STATE_RUNNING\x10\x01\x12\x18\n" +
	"\x14SANDBOX_STATE_PAUSED\x10\x02*\x89\x02\n" +
	"\x0eDataPlaneState\x12 \n" +
	"\x1cDATA_PLANE_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DATA_PLANE_STATE_UNKNOWN\x10\x01\x12\x1c\n" +
	"\x18DATA_PLANE_STATE_PENDING\x10\x02\x12\x1f\n" +
	"\x1bDATA_PLANE_STATE_PUBLISHING\x10\x03\x12\x1a\n" +
	"\x16DATA_PLANE_STATE_READY\x10\x04\x12\x1d\n" +
	"\x19DATA_PLANE_STATE_DRAINING\x10\x05\x12\x1b\n" +
	"\x17DATA_PLANE_STATE_FAILED\x10\x06\x12 \n" +
	"\x1cDATA_PLANE_STATE_UNAVAILABLE\x10\a*A\n" +
	"\x12EndpointAccessMode\x12\x11\n" +
	"\rCENTRAL_PROXY\x10\x00\x12\x18\n" +
	"\x14DIRECT_FASTLET_PROXY\x10\x012\x96\x02\n" +
	"\x0fFastPathService\x12M\n" +
	"\n" +
	"GetSandbox\x12\x1e.fastpath.v2.GetSandboxRequest\x1a\x1f.fastpath.v2.GetSandboxResponse\x12V\n" +
	"\rResumeSandbox\x12!.fastpath.v2.ResumeSandboxRequest\x1a\".fastpath.v2.ResumeSandboxResponse\x12\\\n" +
	"\x0fResolveEndpoint\x12#.fastpath.v2.ResolveEndpointRequest\x1a$.fastpath.v2.ResolveEndpointResponseBCZAgithub.com/alibaba/opensandbox/ingress/pkg/fastpath/v2;fastpathv2b\x06proto3"

var (
	file_fastpath_proto_rawDescOnce sync.Once
	file_fastpath_proto_rawDescData []byte
)

func file_fastpath_proto_rawDescGZIP() []byte {
	file_fastpath_proto_rawDescOnce.Do(func() {
		file_fastpath_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fastpath_proto_rawDesc), len(file_fastpath_proto_rawDesc)))
	})
	return file_fastpath_proto_rawDescData
}

var file_fastpath_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_fastpath_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_fastpath_proto_goTypes = []any{
	(RuntimeState)(0),               // 0: fastpath.v2.RuntimeState
	(SandboxState)(0),               // 1: fastpath.v2.SandboxState
	(DataPlaneState)(0),             // 2: fastpath.v2.DataPlaneState
	(EndpointAccessMode)(0),         // 3: fastpath.v2.EndpointAccessMode
	(*NamespacedName)(nil),          // 4: fastpath.v2.NamespacedName
	(*SandboxReference)(nil),        // 5: fastpath.v2.SandboxReference
	(*SandboxIdentity)(nil),         // 6: fastpath.v2.SandboxIdentity
	(*RuntimeInfo)(nil),             // 7: fastpath.v2.RuntimeInfo
	(*DataPlaneInfo)(nil),           // 8: fastpath.v2.DataPlaneInfo
	(*CheckpointInfo)(nil),          // 9: fastpath.v2.CheckpointInfo
	(*SandboxInfo)(nil),             // 10: fastpath.v2.SandboxInfo
	(*GetSandboxRequest)(nil),       // 11: fastpath.v2.GetSandboxRequest
	(*GetSandboxResponse)(nil),      // 12: fastpath.v2.GetSandboxResponse
	(*ResumeSandboxRequest)(nil),    // 13: fastpath.v2.ResumeSandboxRequest
	(*ResumeSandboxResponse)(nil),   // 14: fastpath.v2.ResumeSandboxResponse
	(*EndpointTarget)(nil),          // 15: fastpath.v2.EndpointTarget
	(*ResolveEndpointRequest)(nil),  // 16: fastpath.v2.ResolveEndpointRequest
	(*ResolvedEndpoint)(nil),        // 17: fastpath.v2.ResolvedEndpoint
	(*ResolveEndpointResponse)(nil), // 18: fastpath.v2.ResolveEndpointResponse
	nil,                             // 19: fastpath.v2.ResolveEndpointResponse.RequiredHeadersEntry
}
var file_fastpath_proto_depIdxs = []int32{
	4,  // 0: fastpath.v2.SandboxReference.namespaced_name:type_name -> fastpath.v2.NamespacedName
	0,  // 1: fastpath.v2.RuntimeInfo.state:type_name -> fastpath.v2.RuntimeState
	2,  // 2: fastpath.v2.DataPlaneInfo.state:type_name -> fastpath.v2.DataPlaneState
	6,  // 3: fastpath.v2.SandboxInfo.identity:type_name -> fastpath.v2.SandboxIdentity
	7,  // 4: fastpath.v2.SandboxInfo.runtime:type_name -> fastpath.v2.RuntimeInfo
	8,  // 5: fastpath.v2.SandboxInfo.data_plane:type_name -> fastpath.v2.DataPlaneInfo
	1,  // 6: fastpath.v2.SandboxInfo.state:type_name -> fastpath.v2.SandboxState
	9,  // 7: fastpath.v2.SandboxInfo.checkpoint:type_name -> fastpath.v2.CheckpointInfo
	5,  // 8: fastpath.v2.GetSandboxRequest.sandbox:type_name -> fastpath.v2.SandboxReference
	10, // 9: fastpath.v2.GetSandboxResponse.sandbox:type_name -> fastpath.v2.SandboxInfo
	5,  // 10: fastpath.v2.ResumeSandboxRequest.sandbox:type_name -> fastpath.v2.SandboxReference
	10, // 11: fastpath.v2.ResumeSandboxResponse.sandbox:type_name -> fastpath.v2.SandboxInfo
	5,  // 12: fastpath.v2.ResolveEndpointRequest.sandbox:type_name -> fastpath.v2.SandboxReference
	15, // 13: fastpath.v2.ResolveEndpointRequest.target:type_name -> fastpath.v2.EndpointTarget
	3,  // 14: fastpath.v2.ResolveEndpointRequest.access_mode:type_name -> fastpath.v2.EndpointAccessMode
	17, // 15: fastpath.v2.ResolveEndpointResponse.endpoint:type_name -> fastpath.v2.ResolvedEndpoint
	19, // 16: fastpath.v2.ResolveEndpointResponse.required_headers:type_name -> fastpath.v2.ResolveEndpointResponse.RequiredHeadersEntry
	11, // 17: fastpath.v2.FastPathService.GetSandbox:input_type -> fastpath.v2.GetSandboxRequest
	13, // 18: fastpath.v2.FastPathService.ResumeSandbox:input_type -> fastpath.v2.ResumeSandboxRequest
	16, // 19: fastpath.v2.FastPathService.ResolveEndpoint:input_type -> fastpath.v2.ResolveEndpointRequest
	12, // 20: fastpath.v2.FastPathService.GetSandbox:output_type -> fastpath.v2.GetSandboxResponse
	14, // 21: fastpath.v2.FastPathService.ResumeSandbox:output_type -> fastpath.v2.ResumeSandboxResponse
	18, // 22: fastpath.v2.FastPathService.ResolveEndpoint:output_type -> fastpath.v2.ResolveEndpointResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_fastpath_proto_init() }
func file_fastpath_proto_init() {
	if File_fastpath_proto != nil {
		return
	}
	file_fastpath_proto_msgTypes[11].OneofWrappers = []any{
		(*EndpointTarget_ComponentName)(nil),
		(*EndpointTarget_Port)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fastpath_proto_rawDesc), len(file_fastpath_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fastpath_proto_goTypes,
		DependencyIndexes: file_fastpath_proto_depIdxs,
		EnumInfos:         file_fastpath_proto_enumTypes,
		MessageInfos:      file_fastpath_proto_msgTypes,
	}.Build()
	File_fastpath_proto = out.File
	file_fastpath_proto_goTypes = nil
	file_fastpath_proto_depIdxs = nil
}
