// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: fastpath.proto

package fastpathv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointAccessMode int32

const (
	EndpointAccessMode_CENTRAL_PROXY        EndpointAccessMode = 0
	EndpointAccessMode_DIRECT_FASTLET_PROXY EndpointAccessMode = 1
)

// Enum value maps for EndpointAccessMode.
var (
	EndpointAccessMode_name = map[int32]string{
		0: "CENTRAL_PROXY",
		1: "DIRECT_FASTLET_PROXY",
	}
	EndpointAccessMode_value = map[string]int32{
		"CENTRAL_PROXY":        0,
		"DIRECT_FASTLET_PROXY": 1,
	}
)

func (x EndpointAccessMode) Enum() *EndpointAccessMode {
	p := new(EndpointAccessMode)
	*p = x
	return p
}

func (x EndpointAccessMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointAccessMode) Descriptor() protoreflect.EnumDescriptor {
	return file_fastpath_proto_enumTypes[0].Descriptor()
}

func (EndpointAccessMode) Type() protoreflect.EnumType {
	return &file_fastpath_proto_enumTypes[0]
}

func (x EndpointAccessMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointAccessMode.Descriptor instead.
func (EndpointAccessMode) EnumDescriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{0}
}

type NamespacedName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespacedName) Reset() {
	*x = NamespacedName{}
	mi := &file_fastpath_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespacedName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacedName) ProtoMessage() {}

func (x *NamespacedName) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacedName.ProtoReflect.Descriptor instead.
func (*NamespacedName) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{0}
}

func (x *NamespacedName) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespacedName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SandboxReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Reference:
	//
	//	*SandboxReference_SandboxUid
	//	*SandboxReference_NamespacedName
	Reference     isSandboxReference_Reference `protobuf_oneof:"reference"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxReference) Reset() {
	*x = SandboxReference{}
	mi := &file_fastpath_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxReference) ProtoMessage() {}

func (x *SandboxReference) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxReference.ProtoReflect.Descriptor instead.
func (*SandboxReference) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxReference) GetReference() isSandboxReference_Reference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *SandboxReference) GetSandboxUid() string {
	if x != nil {
		if x, ok := x.Reference.(*SandboxReference_SandboxUid); ok {
			return x.SandboxUid
		}
	}
	return ""
}

func (x *SandboxReference) GetNamespacedName() *NamespacedName {
	if x != nil {
		if x, ok := x.Reference.(*SandboxReference_NamespacedName); ok {
			return x.NamespacedName
		}
	}
	return nil
}

type isSandboxReference_Reference interface {
	isSandboxReference_Reference()
}

type SandboxReference_SandboxUid struct {
	SandboxUid string `protobuf:"bytes,1,opt,name=sandbox_uid,json=sandboxUid,proto3,oneof"`
}

type SandboxReference_NamespacedName struct {
	NamespacedName *NamespacedName `protobuf:"bytes,2,opt,name=namespaced_name,json=namespacedName,proto3,oneof"`
}

func (*SandboxReference_SandboxUid) isSandboxReference_Reference() {}

func (*SandboxReference_NamespacedName) isSandboxReference_Reference() {}

type EndpointTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*EndpointTarget_ComponentName
	//	*EndpointTarget_Port
	Target        isEndpointTarget_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointTarget) Reset() {
	*x = EndpointTarget{}
	mi := &file_fastpath_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointTarget) ProtoMessage() {}

func (x *EndpointTarget) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointTarget.ProtoReflect.Descriptor instead.
func (*EndpointTarget) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointTarget) GetTarget() isEndpointTarget_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EndpointTarget) GetComponentName() string {
	if x != nil {
		if x, ok := x.Target.(*EndpointTarget_ComponentName); ok {
			return x.ComponentName
		}
	}
	return ""
}

func (x *EndpointTarget) GetPort() uint32 {
	if x != nil {
		if x, ok := x.Target.(*EndpointTarget_Port); ok {
			return x.Port
		}
	}
	return 0
}

type isEndpointTarget_Target interface {
	isEndpointTarget_Target()
}

type EndpointTarget_ComponentName struct {
	ComponentName string `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3,oneof"`
}

type EndpointTarget_Port struct {
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3,oneof"`
}

func (*EndpointTarget_ComponentName) isEndpointTarget_Target() {}

func (*EndpointTarget_Port) isEndpointTarget_Target() {}

type ResolveEndpointRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sandbox           *SandboxReference      `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Target            *EndpointTarget        `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	AccessMode        EndpointAccessMode     `protobuf:"varint,3,opt,name=access_mode,json=accessMode,proto3,enum=fastpath.v2.EndpointAccessMode" json:"access_mode,omitempty"`
	WaitUntilReady    bool                   `protobuf:"varint,4,opt,name=wait_until_ready,json=waitUntilReady,proto3" json:"wait_until_ready,omitempty"`
	WaitTimeoutMillis int32                  `protobuf:"varint,5,opt,name=wait_timeout_millis,json=waitTimeoutMillis,proto3" json:"wait_timeout_millis,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveEndpointRequest) Reset() {
	*x = ResolveEndpointRequest{}
	mi := &file_fastpath_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEndpointRequest) ProtoMessage() {}

func (x *ResolveEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEndpointRequest.ProtoReflect.Descriptor instead.
func (*ResolveEndpointRequest) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveEndpointRequest) GetSandbox() *SandboxReference {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *ResolveEndpointRequest) GetTarget() *EndpointTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ResolveEndpointRequest) GetAccessMode() EndpointAccessMode {
	if x != nil {
		return x.AccessMode
	}
	return EndpointAccessMode_CENTRAL_PROXY
}

func (x *ResolveEndpointRequest) GetWaitUntilReady() bool {
	if x != nil {
		return x.WaitUntilReady
	}
	return false
}

func (x *ResolveEndpointRequest) GetWaitTimeoutMillis() int32 {
	if x != nil {
		return x.WaitTimeoutMillis
	}
	return 0
}

type ResolveEndpointResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SandboxUid           string                 `protobuf:"bytes,1,opt,name=sandbox_uid,json=sandboxUid,proto3" json:"sandbox_uid,omitempty"`
	Target               *EndpointTarget        `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ComponentName        string                 `protobuf:"bytes,3,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Protocol             string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ResolvedPort         uint32                 `protobuf:"varint,5,opt,name=resolved_port,json=resolvedPort,proto3" json:"resolved_port,omitempty"`
	ProxyEndpoint        string                 `protobuf:"bytes,6,opt,name=proxy_endpoint,json=proxyEndpoint,proto3" json:"proxy_endpoint,omitempty"`
	RequiredHeaders      map[string]string      `protobuf:"bytes,7,rep,name=required_headers,json=requiredHeaders,proto3" json:"required_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RouteGeneration      int64                  `protobuf:"varint,8,opt,name=route_generation,json=routeGeneration,proto3" json:"route_generation,omitempty"`
	ExpiresAtUnixSeconds int64                  `protobuf:"varint,9,opt,name=expires_at_unix_seconds,json=expiresAtUnixSeconds,proto3" json:"expires_at_unix_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResolveEndpointResponse) Reset() {
	*x = ResolveEndpointResponse{}
	mi := &file_fastpath_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEndpointResponse) ProtoMessage() {}

func (x *ResolveEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fastpath_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEndpointResponse.ProtoReflect.Descriptor instead.
func (*ResolveEndpointResponse) Descriptor() ([]byte, []int) {
	return file_fastpath_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveEndpointResponse) GetSandboxUid() string {
	if x != nil {
		return x.SandboxUid
	}
	return ""
}

func (x *ResolveEndpointResponse) GetTarget() *EndpointTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ResolveEndpointResponse) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ResolveEndpointResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ResolveEndpointResponse) GetResolvedPort() uint32 {
	if x != nil {
		return x.ResolvedPort
	}
	return 0
}

func (x *ResolveEndpointResponse) GetProxyEndpoint() string {
	if x != nil {
		return x.ProxyEndpoint
	}
	return ""
}

func (x *ResolveEndpointResponse) GetRequiredHeaders() map[string]string {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

func (x *ResolveEndpointResponse) GetRouteGeneration() int64 {
	if x != nil {
		return x.RouteGeneration
	}
	return 0
}

func (x *ResolveEndpointResponse) GetExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.ExpiresAtUnixSeconds
	}
	return 0
}

var File_fastpath_proto protoreflect.FileDescriptor

const file_fastpath_proto_rawDesc = "" +
	"\n" +
	"\x0efastpath.proto\x12\vfastpath.v2\"B\n" +
	"\x0eNamespacedName\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8a\x01\n" +
	"\x10SandboxReference\x12!\n" +
	"\vsandbox_uid\x18\x01 \x01(\tH\x00R\n" +
	"sandboxUid\x12F\n" +
	"\x0fnamespaced_name\x18\x02 \x01(\v2\x1b.fastpath.v2.NamespacedNameH\x00R\x0enamespacedNameB\v\n" +
	"\treference\"Y\n" +
	"\x0eEndpointTarget\x12'\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tH\x00R\rcomponentName\x12\x14\n" +
	"\x04port\x18\x02 \x01(\rH\x00R\x04portB\b\n" +
	"\x06target\"\xa2\x02\n" +
	"\x16ResolveEndpointRequest\x127\n" +
	"\asandbox\x18\x01 \x01(\v2\x1d.fastpath.v2.SandboxReferenceR\asandbox\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.fastpath.v2.EndpointTargetR\x06target\x12@\n" +
	"\vaccess_mode\x18\x03 \x01(\x0e2\x1f.fastpath.v2.EndpointAccessModeR\n" +
	"accessMode\x12(\n" +
	"\x10wait_until_ready\x18\x04 \x01(\bR\x0ewaitUntilReady\x12.\n" +
	"\x13wait_timeout_millis\x18\x05 \x01(\x05R\x11waitTimeoutMillis\"\x8a\x04\n" +
	"\x17ResolveEndpointResponse\x12\x1f\n" +
	"\vsandbox_uid\x18\x01 \x01(\tR\n" +
	"sandboxUid\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.fastpath.v2.EndpointTargetR\x06target\x12%\n" +
	"\x0ecomponent_name\x18\x03 \x01(\tR\rcomponentName\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12#\n" +
	"\rresolved_port\x18\x05 \x01(\rR\fresolvedPort\x12%\n" +
	"\x0eproxy_endpoint\x18\x06 \x01(\tR\rproxyEndpoint\x12d\n" +
	"\x10required_headers\x18\a \x03(\v29.fastpath.v2.ResolveEndpointResponse.RequiredHeadersEntryR\x0frequiredHeaders\x12)\n" +
	"\x10route_generation\x18\b \x01(\x03R\x0frouteGeneration\x125\n" +
	"\x17expires_at_unix_seconds\x18\t \x01(\x03R\x14expiresAtUnixSeconds\x1aB\n" +
	"\x14RequiredHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*A\n" +
	"\x12EndpointAccessMode\x12\x11\n" +
	"\rCENTRAL_PROXY\x10\x00\x12\x18\n" +
	"\x14DIRECT_FASTLET_PROXY\x10\x012o\n" +
	"\x0fFastPathService\x12\\\n" +
	"\x0fResolveEndpoint\x12#.fastpath.v2.ResolveEndpointRequest\x1a$.fastpath.v2.ResolveEndpointResponseBCZAgithub.com/alibaba/opensandbox/ingress/pkg/fastpath/v2;fastpathv2b\x06proto3"

var (
	file_fastpath_proto_rawDescOnce sync.Once
	file_fastpath_proto_rawDescData []byte
)

func file_fastpath_proto_rawDescGZIP() []byte {
	file_fastpath_proto_rawDescOnce.Do(func() {
		file_fastpath_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fastpath_proto_rawDesc), len(file_fastpath_proto_rawDesc)))
	})
	return file_fastpath_proto_rawDescData
}

var file_fastpath_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fastpath_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fastpath_proto_goTypes = []any{
	(EndpointAccessMode)(0),         // 0: fastpath.v2.EndpointAccessMode
	(*NamespacedName)(nil),          // 1: fastpath.v2.NamespacedName
	(*SandboxReference)(nil),        // 2: fastpath.v2.SandboxReference
	(*EndpointTarget)(nil),          // 3: fastpath.v2.EndpointTarget
	(*ResolveEndpointRequest)(nil),  // 4: fastpath.v2.ResolveEndpointRequest
	(*ResolveEndpointResponse)(nil), // 5: fastpath.v2.ResolveEndpointResponse
	nil,                             // 6: fastpath.v2.ResolveEndpointResponse.RequiredHeadersEntry
}
var file_fastpath_proto_depIdxs = []int32{
	1, // 0: fastpath.v2.SandboxReference.namespaced_name:type_name -> fastpath.v2.NamespacedName
	2, // 1: fastpath.v2.ResolveEndpointRequest.sandbox:type_name -> fastpath.v2.SandboxReference
	3, // 2: fastpath.v2.ResolveEndpointRequest.target:type_name -> fastpath.v2.EndpointTarget
	0, // 3: fastpath.v2.ResolveEndpointRequest.access_mode:type_name -> fastpath.v2.EndpointAccessMode
	3, // 4: fastpath.v2.ResolveEndpointResponse.target:type_name -> fastpath.v2.EndpointTarget
	6, // 5: fastpath.v2.ResolveEndpointResponse.required_headers:type_name -> fastpath.v2.ResolveEndpointResponse.RequiredHeadersEntry
	4, // 6: fastpath.v2.FastPathService.ResolveEndpoint:input_type -> fastpath.v2.ResolveEndpointRequest
	5, // 7: fastpath.v2.FastPathService.ResolveEndpoint:output_type -> fastpath.v2.ResolveEndpointResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_fastpath_proto_init() }
func file_fastpath_proto_init() {
	if File_fastpath_proto != nil {
		return
	}
	file_fastpath_proto_msgTypes[1].OneofWrappers = []any{
		(*SandboxReference_SandboxUid)(nil),
		(*SandboxReference_NamespacedName)(nil),
	}
	file_fastpath_proto_msgTypes[2].OneofWrappers = []any{
		(*EndpointTarget_ComponentName)(nil),
		(*EndpointTarget_Port)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fastpath_proto_rawDesc), len(file_fastpath_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fastpath_proto_goTypes,
		DependencyIndexes: file_fastpath_proto_depIdxs,
		EnumInfos:         file_fastpath_proto_enumTypes,
		MessageInfos:      file_fastpath_proto_msgTypes,
	}.Build()
	File_fastpath_proto = out.File
	file_fastpath_proto_goTypes = nil
	file_fastpath_proto_depIdxs = nil
}
