// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: fastpath.proto

package fastpathv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FastPathService_ResolveEndpoint_FullMethodName = "/fastpath.v2.FastPathService/ResolveEndpoint"
)

// FastPathServiceClient is the client API for FastPathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This is the fixed T5 subset of opensandbox-group/fast-sandbox FastPath v2
// at revision e22078237542eea4c0ce17aed938cf96bd352520. Field numbers and the
// fully-qualified RPC name must remain wire-compatible with that source.
type FastPathServiceClient interface {
	ResolveEndpoint(ctx context.Context, in *ResolveEndpointRequest, opts ...grpc.CallOption) (*ResolveEndpointResponse, error)
}

type fastPathServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFastPathServiceClient(cc grpc.ClientConnInterface) FastPathServiceClient {
	return &fastPathServiceClient{cc}
}

func (c *fastPathServiceClient) ResolveEndpoint(ctx context.Context, in *ResolveEndpointRequest, opts ...grpc.CallOption) (*ResolveEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveEndpointResponse)
	err := c.cc.Invoke(ctx, FastPathService_ResolveEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FastPathServiceServer is the server API for FastPathService service.
// All implementations must embed UnimplementedFastPathServiceServer
// for forward compatibility.
//
// This is the fixed T5 subset of opensandbox-group/fast-sandbox FastPath v2
// at revision e22078237542eea4c0ce17aed938cf96bd352520. Field numbers and the
// fully-qualified RPC name must remain wire-compatible with that source.
type FastPathServiceServer interface {
	ResolveEndpoint(context.Context, *ResolveEndpointRequest) (*ResolveEndpointResponse, error)
	mustEmbedUnimplementedFastPathServiceServer()
}

// UnimplementedFastPathServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFastPathServiceServer struct{}

func (UnimplementedFastPathServiceServer) ResolveEndpoint(context.Context, *ResolveEndpointRequest) (*ResolveEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveEndpoint not implemented")
}
func (UnimplementedFastPathServiceServer) mustEmbedUnimplementedFastPathServiceServer() {}
func (UnimplementedFastPathServiceServer) testEmbeddedByValue()                         {}

// UnsafeFastPathServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FastPathServiceServer will
// result in compilation errors.
type UnsafeFastPathServiceServer interface {
	mustEmbedUnimplementedFastPathServiceServer()
}

func RegisterFastPathServiceServer(s grpc.ServiceRegistrar, srv FastPathServiceServer) {
	// If the following call panics, it indicates UnimplementedFastPathServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FastPathService_ServiceDesc, srv)
}

func _FastPathService_ResolveEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).ResolveEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_ResolveEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).ResolveEndpoint(ctx, req.(*ResolveEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FastPathService_ServiceDesc is the grpc.ServiceDesc for FastPathService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FastPathService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fastpath.v2.FastPathService",
	HandlerType: (*FastPathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveEndpoint",
			Handler:    _FastPathService_ResolveEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fastpath.proto",
}
