// Code generated by bpf2go; DO NOT EDIT.
//go:build ebpf && (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64)

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadAudit returns the embedded CollectionSpec for audit.
func loadAudit() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AuditBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load audit: %w", err)
	}

	return spec, err
}

// loadAuditObjects loads audit and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*auditObjects
//	*auditPrograms
//	*auditMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAuditObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAudit()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// auditSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type auditSpecs struct {
	auditProgramSpecs
	auditMapSpecs
}

// auditSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type auditProgramSpecs struct {
	OnCommitCreds *ebpf.ProgramSpec `ebpf:"on_commit_creds"`
	OnConnect     *ebpf.ProgramSpec `ebpf:"on_connect"`
	OnExec        *ebpf.ProgramSpec `ebpf:"on_exec"`
}

// auditMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type auditMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// auditObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAuditObjects or ebpf.CollectionSpec.LoadAndAssign.
type auditObjects struct {
	auditPrograms
	auditMaps
}

func (o *auditObjects) Close() error {
	return _AuditClose(
		&o.auditPrograms,
		&o.auditMaps,
	)
}

// auditMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAuditObjects or ebpf.CollectionSpec.LoadAndAssign.
type auditMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *auditMaps) Close() error {
	return _AuditClose(
		m.Events,
	)
}

// auditPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAuditObjects or ebpf.CollectionSpec.LoadAndAssign.
type auditPrograms struct {
	OnCommitCreds *ebpf.Program `ebpf:"on_commit_creds"`
	OnConnect     *ebpf.Program `ebpf:"on_connect"`
	OnExec        *ebpf.Program `ebpf:"on_exec"`
}

func (p *auditPrograms) Close() error {
	return _AuditClose(
		p.OnCommitCreds,
		p.OnConnect,
		p.OnExec,
	)
}

func _AuditClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed audit_bpfel.o
var _AuditBytes []byte
